### ISSUE TITLE
Please push artifacts to MavenCentral

### ISSUE THREAD

**Issue by timmolter** [eseifert/vectorgraphics2d#6]
Just letting you know, I love your library and would love to see it on MavenCentral. :)

**Comment by timmolter** [comment]
I just changed my project's namespace and had to go through the entire process again. I updated my how-to guide, not leaving out a single detail. It's actually not that hard to do. Would love it if you put your jar on Maven Central!

<http://knowm.org/a-practical-guide-to-uploading-artifacts-to-maven-central/>

**Comment by dvayanu** [comment]
Hi, is there any progress on it? We are using your lib with great joy, but other users can't build it, because the artifact isn't found: 
Failure to find de.erichseifert.vectorgraphics2d:VectorGraphics2D:jar:0.9.1

**Comment by seifertm** [comment]
Did you add the Maven repository ``http://mvn.erichseifert.de/maven2`` to the list of repositories in your build system?

In Gradle, you can do:

    repositories {
      mavenLocal()
      maven { url "http://mvn.erichseifert.de/maven2" }
      mavenCentral()
    }

For Maven, you could do something like:

  <repositories>
  <repository>
      <id>de.erichseifert.vectorgraphics2d</id>
      <name>VectorGraphics2D releases</name>
      <url>http://mvn.erichseifert.de/maven2</url>
    </repository>
  </repositories>

(Not 100% sure if the Maven solution works, though)

**Comment by seifertm** [comment]
Did you add the Maven repository ``http://mvn.erichseifert.de/maven2`` to the list of repositories in your build system?

In Gradle, you can do:

    repositories {
      mavenLocal()
      maven { url "http://mvn.erichseifert.de/maven2" }
      mavenCentral()
    }

For Maven, you could do something like:

  <repositories>
  <repository>
      <id>de.erichseifert.vectorgraphics2d</id>
      <name>VectorGraphics2D releases</name>
      <url>http://mvn.erichseifert.de/maven2</url>
    </repository>
  </repositories>

(Not 100% sure if the Maven solution works, though)

**Comment by dvayanu** [comment]
Hi Michael,
thank you for your answer. However the problem is a little bit more subtle and I haven't described it well.
However I described it here: in more detail. Maybe you want to take a look?

http://stackoverflow.com/questions/33396680/maven-dependency-from-transitive-repository-unstable

regards
Leon

**Comment by seifertm** [comment]
Hmm... not sure about it. Seems like a problem of the build system, though.

We will see to it on Sunday.

**Comment by dvayanu** [comment]
I think I found it out, the problem was that the settings.xml on the target system hat a mirror entry <mirrorOf>*</mirrorOf>
Two way to handle it, 1) change * to "central", 2) manually upload your artifact to local mirror... (or add your repo as proxy).
nevertheless, I think it would be better to have the artifact in central... like in maven's way to do things ;-)

thanks and regards
Leon

**Comment by eseifert** [comment]
Just opened a JIRA issue for VectorGraphics2D: https://issues.sonatype.org/browse/OSSRH-18611

**Comment by eseifert** [comment]
I just released VectorGraphics2D 0.9.3 on MavenCentral. The release doesn't contain any changes except the distribution to MavenCentral.

**Comment by timmolter** [comment]
Thanks!
